// import 'dart:ui';
// import 'package:flutter/material.dart';

// import './models/product.dart';

// final List<Product> dummyData = [
//   Product(
//     id: 'p1',
//     titleEn: 'Bananas',
//     titleAr: 'موز',
//     price: 1.15,
//     priceDescriptionEn: 'Per Kilo',
//     priceDescriptionAr: 'للكيلو',
//     imageUrl: 'assets/images/bananas1.png',
//     color: Colors.yellow, //Color(0xFFFEF234), //Color(0xFFF4E389),
//     type: Type.Fruits,
//   ),
//   Product(
//     id: 'p2',
//     titleEn: 'Figs',
//     titleAr: 'تين',
//     price: 14.80,
//     priceDescriptionEn: 'Per Kilo',
//     priceDescriptionAr: 'للكيلو',
//     imageUrl: 'assets/images/figs.png',
//     color: Color(0xFF8B84F3), //Color(0xFFDFDFF8),
//     type: Type.Fruits,
//   ),
//   Product(
//     id: 'p3',
//     titleEn: 'Parsley',
//     titleAr: 'بقدونس',
//     color: Color(0xFF79DE64),
//     price: 2.45,
//     priceDescriptionEn: 'Per Unit',
//     priceDescriptionAr: 'للحبة',
//     imageUrl: 'assets/images/parsley.png',
//     type: Type.Herbs,
//   ),
//   Product(
//     id: 'p4',
//     titleEn: 'Mango',
//     titleAr: 'مانجو',
//     price: 1.02,
//     color: Color(0xFFFF8D22), //Color(0xFFF8DA8A),
//     priceDescriptionEn: 'Per Box',
//     priceDescriptionAr: 'للصندوق',
//     imageUrl: 'assets/images/mango.png',
//     type: Type.Fruits,
//   ),
//   Product(
//     id: 'p5',
//     titleEn: 'Cactus',
//     titleAr: 'تين شوكي',
//     //Color(0xFFEAB9E7),
//     color: Color(0xFFEC75EA),
//     price: 5.36,
//     priceDescriptionEn: 'Per Box',
//     priceDescriptionAr: 'للصندوق',
//     imageUrl: 'assets/images/cactus.png',
//     type: Type.Fruits,
//   ),
//   Product(
//     id: 'p6',
//     titleEn: 'Tomatoes',
//     titleAr: 'طماطم',
//     //Color(0xFFFCE0E2),
//     color: Color(0xFFFF3B4A),
//     price: 1.45,
//     priceDescriptionEn: 'Per Bag',
//     priceDescriptionAr: 'للكيس',
//     imageUrl: 'assets/images/tomatoes.png',
//     type: Type.Vegetables,
//   ),
//   Product(
//     id: 'p7',
//     titleEn: 'Grapes',
//     titleAr: 'عنب',
//     //Color(0xFFB4E0AA),
//     color: Color(0xFF79DE64),
//     price: 8.22,
//     priceDescriptionEn: 'Per Kilo',
//     priceDescriptionAr: 'للكيلو',
//     imageUrl: 'assets/images/grapes.png',
//     type: Type.Fruits,
//   ),
//   Product(
//     id: 'p8',
//     titleEn: 'Carrots',
//     titleAr: 'جزر',
//     //Color(0xFFFFB570),
//     color: Color(0xFFFF8D22),
//     price: 1.99,
//     priceDescriptionEn: 'Per Kilo',
//     priceDescriptionAr: 'للكيلو',
//     imageUrl: 'assets/images/carots.png',
//     type: Type.Vegetables,
//   ),
//   Product(
//     id: 'p9',
//     titleEn: 'Lemons',
//     titleAr: 'ليمون',
//     //Color(0xFFFCF8D5),
//     color: Color(0xFFFEF234),
//     price: 3.55,
//     priceDescriptionEn: 'Per Kilo',
//     priceDescriptionAr: 'للكيلو',
//     imageUrl: 'assets/images/lemon.png',
//     type: Type.Vegetables,
//   ),
//   Product(
//     id: 'p10',
//     titleEn: 'Watermelon',
//     titleAr: 'بطيخ',
//     //Color(0xFFFCE0E2),
//     color: Color(0xFFFF3B4A),
//     price: 2.45,
//     priceDescriptionEn: 'Per Unit',
//     priceDescriptionAr: 'للحبة',
//     imageUrl: 'assets/images/watermelon.png',
//     type: Type.Fruits,
//   ),
//   Product(
//     id: 'p11',
//     titleEn: 'Mint',
//     titleAr: 'نعناع',
//     color: Color(0xFF79DE64),
//     price: 2.45,
//     priceDescriptionEn: 'Per Unit',
//     priceDescriptionAr: 'للحبة',
//     imageUrl: 'assets/images/mint.png',
//     type: Type.Herbs,
//   ),
// ];

// final List<Product> dummyHistoryData = [
//   Product(
//     id: 'p1',
//     titleEn: 'bananas',
//     titleAr: 'موز',
//     price: 1.15,
//     priceDescriptionEn: 'Per Kilo',
//     priceDescriptionAr: 'للكيلو',
//     imageUrl: 'assets/images/bananas1.png',
//     color: Color(0xFFFEF234), //Color(0xFFF4E389),
//     type: Type.Fruits,
//   ),
//   Product(
//     id: 'p2',
//     titleEn: 'figs',
//     titleAr: 'تين',
//     price: 14.80,
//     priceDescriptionEn: 'Per Kilo',
//     priceDescriptionAr: 'للكيلو',
//     imageUrl: 'assets/images/figs.png',
//     color: Color(0xFF8B84F3), //Color(0xFFDFDFF8),
//     type: Type.Fruits,
//   ),
//   Product(
//     id: 'p3',
//     titleEn: 'parsley',
//     titleAr: 'بقدونس',
//     color: Color(0xFF79DE64),
//     price: 2.45,
//     priceDescriptionEn: 'Per Unit',
//     priceDescriptionAr: 'للحبة',
//     imageUrl: 'assets/images/parsley.png',
//     type: Type.Herbs,
//   ),
// ];